version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase...
      # Here, you can add any steps necessary before the application runs, 
      # such as linting or unit tests.
  build:
    commands:
      - echo Build phase, primarily used for compiling or testing in this context...
      # Since there's no compilation step, you might use this phase for running tests.
      # e.g., npm test (if you have tests configured)
  post_build:
    commands:
      - echo Build completed on `date`
      # Any actions after the build, like cleanup or notifications.
artifacts:
  files:
    - '**/*' # Specify the files to include in the output artifact
  discard-paths: no
